language: java
dist: trusty

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak

install: true

script:
  - ./.travis-publish.sh

sudo: false
